[[plugins]] # coc.nvim
repo = 'neoclide/coc.nvim'
rev = 'release'
# rev = 'master'
# build = 'yarn install --frozen-lockfile' # NOTE: masterの場合のみ
depends = ['vim-snippets', 'fzf']
on_event = ['CursorMoved', 'FileType']
on_cmd = ['CocCommand']
lua_add = '''
require("plugins.lsp.coc").lua_add()
'''
lua_source = '''
require("plugins.lsp.coc").lua_source()
'''

# NOTE: こいつはcocのfzf-previewでしか使ってないからここに置いてる
[[plugins]] # fzf
repo = 'junegunn/fzf'
build = './install'
on_source = ['coc.nvim']

