[[plugins]] # dein.vim
# NOTE: ここに入れておかないとヘルプタグが追加されない
repo = 'Shougo/dein.vim'

[[plugins]] # 日本語ドキュメント
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
" ヘルプを日本語化
set helplang=ja
'''

# FIXME: シェルスクリプトのときバグるので一旦オフに
# [[plugins]] # 標準機能より高速にファイル形式を判別できる。
# repo = 'nathom/filetype.nvim'
# hook_add = '''
# " 標準機能をオフに
# let g:did_load_filetypes = 1
# '''
################################################################################
# denops
# NOTE: denops製は遅延いらんらしい
################################################################################
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = ['denops']
lua_add = '''
require("plugins.coding.skkeleton").lua_add()
'''

[[plugins]]
repo = 'lambdalisue/gin.vim'
lua_add = '''
require("plugins.git.gin").lua_add()
'''
################################################################################
# UI
################################################################################
[[plugins]] # airlineをこれに変えたら起動速度が倍速になった
repo = 'nvim-lualine/lualine.nvim'
depends = ['nvim-web-devicons']
lua_add = '''
require("plugins.ui.lualine").timer_start(vim.g["my#const"].timer_start_lualine)
'''

[[plugins]] # 上のbar
repo = 'akinsho/bufferline.nvim'
lua_add = '''
require("plugins.ui.bufferline").timer_start(vim.g["my#const"].timer_start_bufferline)
'''

[[plugins]] # スクロールバー
repo= 'petertriho/nvim-scrollbar'
lua_add = '''
require("plugins.ui.scrollbar").timer_start(vim.g["my#const"].timer_start_scrollbar)
'''

[[plugins]] # notification manager
repo = 'rcarriga/nvim-notify'
################################################################################
# ColorScheme
################################################################################
[[plugins]]
repo = 'ellisonleao/gruvbox.nvim'

[[plugins]]
repo = 'bluz71/vim-nightfly-colors'
lua_add = '''
require("plugins.colorscheme.nightfly").settings()
'''

[[plugins]]
repo = 'EdenEast/nightfox.nvim'

[[plugins]]
repo = 'catppuccin/nvim'

[[plugins]]
repo = 'sainnhe/sonokai'

[[plugins]]
repo = 'shaunsingh/moonlight.nvim'

[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
repo = 'shaunsingh/nord.nvim'

[[plugins]]
repo = 'tanvirtin/monokai.nvim'

[[plugins]]
repo = 'RRethy/nvim-base16'

[[plugins]]
repo = 'rebelot/kanagawa.nvim'
