[[plugins]] # dein.vim
# NOTE: ここに入れておかないとヘルプタグが追加されない
repo = 'Shougo/dein.vim'

[[plugins]] # 日本語ドキュメント
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
" ヘルプを日本語化
set helplang=ja
'''

[[plugins]] # luaモジュールの読み込みを速くするやつ
repo = 'lewis6991/impatient.nvim'
hook_add = '''
lua require('impatient')
'''

# FIXME: シェルスクリプトのときバグるので一旦オフに
# [[plugins]] # 標準機能より高速にファイル形式を判別できる。
# repo = 'nathom/filetype.nvim'
# depends = ['impatient.nvim']
# hook_add = '''
# " 標準機能をオフに
# let g:did_load_filetypes = 1
# '''

[[plugins]] # airlineをこれに変えたら起動速度が倍速になった
repo = 'nvim-lualine/lualine.nvim'
depends = ['nvim-web-devicons', 'impatient.nvim']
lua_add = '''
require("plugins.ui").lua_add_lualine()
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = ['denops']
hook_add = '''
call plugins#code_editting#hook_add_skkeleton()
'''
################################################################################
# ColorScheme
################################################################################
# [[plugins]]
# repo = 'ellisonleao/gruvbox.nvim'
# depends = ['impatient.nvim']
# lua_add = '''
# require("plugins.ui").lua_add_gruvbox()
# '''

# [[plugins]]
# repo = 'bluz71/vim-nightfly-colors'
# depends = ['impatient.nvim']
# lua_add = '''
# require("plugins.ui").lua_add_nightfly_colors()
# '''

[[plugins]]
repo = 'EdenEast/nightfox.nvim'
depends = ['impatient.nvim']
lua_add = '''
require("plugins.ui").lua_add_nightfox()
'''

