[[plugins]] # dein.vim
# NOTE: ここに入れておかないとヘルプタグが追加されない
repo = 'Shougo/dein.vim'

[[plugins]] # 日本語ドキュメント
# NOTE: luaのドキュメントを読むには↓
# :h nvim-lua-guide.txt
repo = 'vim-jp/vimdoc-ja'

[[plugins]] # 標準機能より高速にファイル形式を判別できる。
repo = 'nathom/filetype.nvim'
hook_add = '''
" 標準機能をオフに
let g:did_load_filetypes = 1
'''

[[plugins]] # luaモジュールの読み込みを速くするやつ
repo = 'lewis6991/impatient.nvim'
hook_add = '''
lua require('impatient')
'''

[[plugins]] # airline-themes
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
call MyPluginSettings#hook_add_airline_themes()
'''

[[plugins]] # airline
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes', 'vim-fugitive']
hook_add = '''
call MyPluginSettings#hook_add_airline()
'''

[[plugins]] # colorscheme
repo = 'RRethy/nvim-base16'
hook_add = '''
call MyPluginSettings#hook_add_base16()
'''
