[[plugins]] # dein.vim
# NOTE: ここに入れておかないとヘルプタグが追加されない
repo = 'Shougo/dein.vim'

[[plugins]] # 日本語ドキュメント
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
" ヘルプを日本語化
set helplang=ja
'''

[[plugins]] # luaモジュールの読み込みを速くするやつ
repo = 'lewis6991/impatient.nvim'
hook_add = '''
lua require('impatient')
'''

# FIXME: シェルスクリプトのときバグるので一旦オフに
# [[plugins]] # 標準機能より高速にファイル形式を判別できる。
# repo = 'nathom/filetype.nvim'
# depends = ['impatient.nvim']
# hook_add = '''
# " 標準機能をオフに
# let g:did_load_filetypes = 1
# '''
################################################################################
# denops
# NOTE: denops製は遅延いらんらしい
################################################################################
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = ['denops']
lua_add = '''
require("plugins.coding").lua_add_skkeleton()
'''

[[plugins]]
repo = 'lambdalisue/gin.vim'
lua_add = '''
require("plugins.git").lua_add_gin()
'''
################################################################################
# UI
################################################################################
[[plugins]] # airlineをこれに変えたら起動速度が倍速になった
repo = 'nvim-lualine/lualine.nvim'
depends = ['nvim-web-devicons', 'impatient.nvim']
lua_add = '''
require("plugins.ui").timer_start_lualine(vim.g["my#const"].timer_start_lualine)
'''

[[plugins]] # 上のbar
repo = 'akinsho/bufferline.nvim'
lua_add = '''
require("plugins.ui").timer_start_bufferline(vim.g["my#const"].timer_start_bufferline)
'''

[[plugins]] # スクロールバー
repo= 'petertriho/nvim-scrollbar'
lua_add = '''
require("plugins.ui").timer_start_scrollbar(vim.g["my#const"].timer_start_scrollbar)
'''
################################################################################
# ColorScheme
################################################################################
[[plugins]]
repo = 'morhetz/gruvbox'
depends = ['impatient.nvim']

[[plugins]]
repo = 'bluz71/vim-nightfly-colors'
depends = ['impatient.nvim']

[[plugins]]
repo = 'EdenEast/nightfox.nvim'
depends = ['impatient.nvim']

[[plugins]]
repo = 'catppuccin/nvim'
depends = ['impatient.nvim']

[[plugins]]
repo = 'sainnhe/sonokai'
depends = ['impatient.nvim']

[[plugins]]
repo = 'shaunsingh/moonlight.nvim'
depends = ['impatient.nvim']

[[plugins]]
repo = 'folke/tokyonight.nvim'
depends = ['impatient.nvim']

[[plugins]]
repo = 'shaunsingh/nord.nvim'
depends = ['impatient.nvim']

[[plugins]]
repo = 'tanvirtin/monokai.nvim'
depends = ['impatient.nvim']

[[plugins]]
repo = 'Scysta/pink-panic.nvim'
depends = ['impatient.nvim', 'lush.nvim']

[[plugins]]
repo = 'RRethy/nvim-base16'
depends = ['impatient.nvim']
