[[plugins]] # 日本語ドキュメント
 # NOTE: luaのドキュメントを読むには↓
# :h nvim-lua-guide.txt
repo = 'vim-jp/vimdoc-ja'

[[plugins]] # アイコン類
repo = 'ryanoasis/vim-devicons'

[[plugins]] # colorscheme
repo = 'RRethy/nvim-base16'
hook_add = '''
call MyPluginSettings#hook_add_base16()
'''
[[plugins]] # airline-themes
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
call MyPluginSettings#hook_add_airline_themes()
'''

[[plugins]] # airline
repo = 'vim-airline/vim-airline'
depends =['vim-airline-themes', 'vim-fugitive']
hook_add = '''
call MyPluginSettings#hook_add_airline()
'''

