[[plugins]] # nvim-treesitter
# NOTE: デフォルトのシンタックスハイライトは色が少なくて見づらい
# これを入れるだけであらゆるファイルタイプのシンタックスハイライトが見やすくなる
# 逆にデフォルトの方が見やすい場合はtreesitterを適宜オフに設定する
repo = 'nvim-treesitter/nvim-treesitter'
on_event = ['BufRead', 'InsertEnter', 'FileType']
hook_source = '''
call MyPluginSettings#hook_source_treesitter()
'''

[[plugins]] # vimでgitを実行するやつ
# NOTE: :Git xxでgitコマンドを実行できる
# TODO: on_cmdにして全コマンドを指定
repo = 'tpope/vim-fugitive'
on_event = ['BufRead']

[[plugins]] # VSCodeのGitLens的なやつ
repo = 'APZelos/blamer.nvim'
depends = ['tpope/vim-fugitive']
on_cmd = ['BlamerHide', 'BlamerShow', 'BlamerToggle']
hook_add = '''
call MyPluginSettings#hook_add_blamer()
'''

[[plugins]] # vimから編集中のファイルを素早く実行するやつ
# FIXME: 実行結果を右ではなく下に小さく表示させたい
repo = 'thinca/vim-quickrun'
on_cmd = ['QuickRun']
hook_add = '''
nnoremap <F5> :QuickRun<CR>
vnoremap <F5> :QuickRun<CR>
'''

[[plugins]] # editorconfig
repo = 'editorconfig/editorconfig-vim'
on_event = ['BufRead']

[[plugins]] # インデント可視化
repo = 'lukas-reineke/indent-blankline.nvim'
on_event = ['BufRead', 'InsertEnter']
hook_source = '''
call MyPluginSettings#hook_source_indent_blankline()
'''

[[plugins]] # 対のカッコをハイライト
repo = 'itchyny/vim-parenmatch'
on_event = ['BufRead', 'InsertEnter']
hook_add = '''
" NOTE: 標準プラグインのmatchparenを無効化
let g:loaded_matchparen = 1
'''

[[plugins]] # 行内ジャンプ用にハイライトしてくれるやつ
# TODO しばらく試してみていらなかったら消す
repo = 'unblevable/quick-scope'
on_event = ['BufRead', 'InsertEnter']

# [[plugins]] # コメントアウト
# repo = 'tyru/caw.vim'
# on_event = []
# hook_source = '''
# call MyPluginSettings#hook_source_caw()
# '''

[[plugins]] # コメントアウト
repo = 'tpope/vim-commentary'
on_event = ['BufRead', 'InsertEnter']
hook_source = '''
call MyPluginSettings#hook_source_commentary()
'''

[[plugins]] # 括弧、クォーテーション、タグを自動で閉じてくれるプラグイン(自作)
repo = 'ukiuki-engineer/vim-autoclose'
on_event = ['BufRead', 'InsertEnter']

[[plugins]] # blade
repo = 'jwalton512/vim-blade'
on_if = 'expand("%") =~ "blade\.php"'
on_ft = ['blade']

[[plugins]] # カラーコード可視化
repo = 'norcalli/nvim-colorizer.lua'
on_ft = ['css', 'html', 'less', 'sass', 'scss', 'stylus', 'vim', 'blade', 'vue', 'eruby', 'toml']
hook_source = '''
call MyPluginSettings#hook_source_colorizer()
'''
lua_post_source = '''
require 'colorizer'.setup()
'''

[[plugins]] # ヘルプファイル自動生成
repo = 'LeafCage/vimhelpgenerator'
on_cmd = ['VimHelpGenerator', 'VimHelpGeneratorVirtual']
hook_source = '''
call MyPluginSettings#hook_source_colorizer()
'''

[[plugins]] # markdownでtable作成
repo = 'mattn/vim-maketable'
on_ft = 'markdown'

[[plugins]] # コマンドの実行結果をバッファに読み込んでくれるやつ
repo = 'numEricL/vim-redirect'
on_cmd = ['Redirect']

[[plugins]] # アイコン類
repo = 'ryanoasis/vim-devicons'
on_source = ['airline', 'nerdtree']

# [[plugins]]
# repo = 'folke/noice.nvim'
# on_event = ['BufRead']
# depends = ['MunifTanjim/nui.nvim', 'rcarriga/nvim-notify', 'nvim-treesitter/nvim-treesitter']
# hook_add = '''
# lua << EOF
#   require("noice").setup({
#     lsp = {
#       -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
#       override = {
#         ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
#         ["vim.lsp.util.stylize_markdown"] = true,
#         ["cmp.entry.get_documentation"] = true,
#       },
#     },
#     -- you can enable a preset for easier configuration
#     presets = {
#       bottom_search = true, -- use a classic bottom cmdline for search
#       command_palette = true, -- position the cmdline and popupmenu together
#       long_message_to_split = true, -- long messages will be sent to a split
#       inc_rename = false, -- enables an input dialog for inc-rename.nvim
#       lsp_doc_border = false, -- add a border to hover docs and signature help
#     },
#   })
# EOF
# '''

# [[plugins]]
# repo = 'MunifTanjim/nui.nvim'
# on_event = ['BufRead']

# [[plugins]]
# repo = 'rcarriga/nvim-notify'
# on_event = ['BufRead']

[[plugins]] # ファイラー
repo = 'scrooloose/nerdtree'
depends = ['ryanoasis/vim-devicons']
on_cmd = [
  'NERDTree',
  'NERDTree',
  'NERDTreeCWD',
  'NERDTreeClose',
  'NERDTreeFind',
  'NERDTreeFocus',
  'NERDTreeFromBookmark',
  'NERDTreeMirror',
  'NERDTreeRefreshRoot',
  'NERDTreeSetting',
  'NERDTreeShowHidden',
  'NERDTreeToggle',
  'NERDTreeToggleVCS',
  'NERDTreeVCS'
]
hook_add = '''
call MyPluginSettings#hook_add_nerdtree()
'''

[[plugins]] # ファジーファインダー
repo = 'junegunn/fzf'
on_event = ['BufRead']
build = './install'

[[plugins]] # ファジーファインダー
# NOTE: プレビューウィンドウをハイライトするには、batをインストールする
# →brew install bat
repo = 'junegunn/fzf.vim'
# NOTE: こっちでもいい→on_source = ['fzf']
on_cmd = [
  'Files',
  'GFiles',
  'GFiles?',
  'Buffers',
  'Colors',
  'Ag',
  'Rg',
  'Lines',
  'BLines',
  'Tags',
  'BTags',
  'Marks',
  'Windows',
  'Locate PATTERN',
  'History',
  'History:',
  'History/',
  'Snippets',
  'Commits',
  'BCommits',
  'Commands',
  'Maps',
  'Helptags',
  'Filetypes'
]
depends = 'junegunn/fzf'
hook_add = '''
call MyPluginSettings#hook_add_fzf()
'''

[[plugins]] # vimの起動速度を測定
repo = 'dstein64/vim-startuptime'
on_cmd = ['StartupTime']

[[plugins]] # スニペットのソース類
# NOTE: coc-snippetsで呼び出して使う
# 個々のcocプラグイン側の補完候補とぶつかって面倒な場合はどちらかをオフにする
repo = 'honza/vim-snippets'
on_event = ['BufRead', 'InsertEnter', 'FileType']

[[plugins]] # coc.nvim
# FIXME: erubyでjavascriptのsnippetsを使いたい(もうruby触ることないけど...)
# FIXME: bladeでも、phpの関数のhoverが読みたい
# NOTE: coc-bladeは、"b:xxx"と打つと補完候補が出る
# NOTE: :CocCommand xx.xxで各拡張機能のコマンドを色々呼び出せる
# NOTE: :CocCommand cSpell.addWordToDictionaryでスペルチェックの例外追加
# NOTE: Laravel固有のメソッドに対して補完やホバーを行うには、補完ヘルパーファイルを出力する必要がある
# 手順は以下の通り
# composer require --dev barryvdh/laravel-ide-helper # ライブラリをインストール
# php artisan ide-helper:generate                    # _ide_helper.phpを生成
# php artisan ide-helper:models --nowrite            # _ide_helper_models.phpを生成
repo = 'neoclide/coc.nvim'
rev = 'release'
on_event = ['BufRead', 'InsertEnter', 'FileType']
hook_add = '''
call MyPluginSettings#hook_add_coc()
'''
