[[plugins]] # dein.vim
# NOTE: ここに入れておかないとヘルプタグが追加されない
repo = 'Shougo/dein.vim'

[[plugins]] # 日本語ドキュメント
repo = 'vim-jp/vimdoc-ja'

[[plugins]] # luaモジュールの読み込みを速くするやつ
repo = 'lewis6991/impatient.nvim'
hook_add = '''
lua require('impatient')
'''

[[plugins]] # 標準機能より高速にファイル形式を判別できる。
repo = 'nathom/filetype.nvim'
depends = ['impatient.nvim']
hook_add = '''
" 標準機能をオフに
let g:did_load_filetypes = 1
'''

[[plugins]] # airlineをこれに変えたら起動速度が倍速になった
repo = 'nvim-lualine/lualine.nvim'
depends = ['nvim-web-devicons', 'impatient.nvim']
lua_add = '''
require("my_plugin_settings").lua_add_lualine()
'''

# [[plugins]] # カラースキーム
# repo = 'ellisonleao/gruvbox.nvim'
# depends = ['impatient.nvim']
# lua_add = '''
# require("my_plugin_settings").lua_add_gruvbox()
# '''

[[plugins]] # カラースキーム
repo = 'bluz71/vim-nightfly-colors'
depends = ['impatient.nvim']
lua_add = '''
require("my_plugin_settings").lua_add_nightfly_colors()
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

