# NOTE: 今使ってないやつは一旦ここに(コメントアウトだと邪魔)

[[plugins]] # colorscheme
repo = 'RRethy/nvim-base16'
hook_add = '''
call plugins#hook_add_base16()
'''

[[plugins]]
repo = 'marko-cerovac/material.nvim'
hook_add = '''
call plugins#hook_add_material()
'''

[[plugins]] # 対のカッコをハイライト
repo = 'itchyny/vim-parenmatch'
on_event = ['BufRead', 'InsertEnter']
hook_add = '''
" NOTE: 標準プラグインのmatchparenを無効化
let g:loaded_matchparen = 1
'''

[[plugins]] # 行番号の左に、gitの状態を表示するやつ
repo = 'airblade/vim-gitgutter'
on_event = ['BufRead']
hook_source = '''
call plugins#git#hook_source_gitgutter()
'''
