# NOTE: 今使ってないやつは一旦ここに(コメントアウトだと邪魔)

[[plugins]] # colorscheme
repo = 'RRethy/nvim-base16'
hook_add = '''
call MyPluginSettings#hook_add_base16()
'''

[[plugins]]
repo = 'bluz71/vim-nightfly-colors'
hook_add = '''
colorscheme nightfly
'''

[[plugins]]
repo = 'marko-cerovac/material.nvim'
hook_add = '''
call MyPluginSettings#hook_add_material()
'''

[[plugins]] # vim内部で日本語入力するためのプラグイン
# FIXME: 試しに入れてみたけど、使いこなすには色々設定がいりそう...
#        時間取れるときにゆっくり設定を作りこむ
repo = 'vim-skk/eskk.vim'
on_event = ['BufRead', 'InsertEnter']
hook_add = '''
call MyPluginSettings#hook_add_eskk()
'''

